name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: LOG
      run: ls -la && pwd

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t cpandax/sharp-heic-layer:latest .
        docker push cpandax/sharp-heic-layer:latest

    # - name: Build Docker image
    #   run: docker build -t sharp-heic-layer .

    # - name: Create Docker Mount Folder
    #   run: mkdir docker-mount

    # - name: Show Contents Before Docker Run
    #   run: ls -l docker-mount

    - name: Run Docker Container with Volume Mount
      run: |
        docker run -d -p 9000:8080 cpandax/sharp-heic-layer

    - name: Wait for container to start
      run: sleep 5

    # - name: Show Contents After Docker Run
    #   run: ls -l docker-mount
    
    - name: Test Lambda function locally 1
      run: |
        curl -X POST \
             -H "Content-Type: application/json" \
             -d '{"key": "value"}' \
             http://localhost:9000/2015-03-31/functions/function/invocations
    
    - name: Test Lambda function locally 2
      id: curl_request
      run: |
        response=$(curl -X POST \
                       -H "Content-Type: application/json" \
                       -d '{"key": "value"}' \
                       http://localhost:9000/2015-03-31/functions/function/invocations)
        echo "$response"

    - name: Copy build artifact to host
      run: docker cp $(docker ps -q --filter ancestor=cpandax/sharp-heic-layer):/var/task/.aws-sam/build/SharpHEICLayer/build.zip $(pwd)/build.zip && pwd && ls -la

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build.zip

    - name: Stop and remove Docker container
      run: docker stop $(docker ps -q --filter ancestor=cpandax/sharp-heic-layer) && docker rm $(docker ps -aq --filter ancestor=cpandax/sharp-heic-layer)