name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t sharp-heic-layer .
    
    - name: Run Docker container
      run: docker run -d -p 9000:8080 sharp-heic-layer

    - name: Wait for container to start
      run: sleep 5
    
    - name: Test Lambda function locally 1
      run: |
        curl -X POST \
             -H "Content-Type: application/json" \
             -d '{"key": "value"}' \
             http://localhost:9000/2015-03-31/functions/function/invocations
    
    - name: Test Lambda function locally 2
      id: curl_request
      run: |
        response=$(curl -X POST \
                       -H "Content-Type: application/json" \
                       -d '{"key": "value"}' \
                       http://localhost:9000/2015-03-31/functions/function/invocations)
        echo "$response"

    - name: Stop and remove Docker container
      run: docker stop $(docker ps -q --filter ancestor=sharp-heic-layer) && docker rm $(docker ps -aq --filter ancestor=sharp-heic-layer)